### ISSUE TITLE
如何查看您的DAPE核心代码呢

### ISSUE THREAD

**Issue by ZK-Zhou** [chuanyang-Zheng/CAPE#1]
作者您好，感谢您的开源。我想快速上手DAPE，在哪个文件中查看DAPE核心代码呢？

**Comment by chuanyang-Zheng** [comment]
Thank you very much for your interest in our work. For the details implementation of DAPE, you may check here: https://github.com/chuanyang-Zheng/DAPE/blob/main/DAPE.py#L295

For the DAPE in GPT-NeoX, you may check
1. megatron/model/transformer.py: https://github.com/chuanyang-Zheng/DAPE/blob/main/megatron/model/transformer.py#L666
2. megatron/model/position_embeddings.py: https://github.com/chuanyang-Zheng/DAPE/blob/main/megatron/model/positional_embeddings.py#L893
If there are any other questions, please let me know.

Again, thank you very much for your attention, and wish you a good day.

Best regards,
Chuanyang

**Comment by ZK-Zhou** [comment]
感谢您的回复，祝愿科研顺利。
